### ISSUE TITLE
大佬您好

### ISSUE THREAD

**Issue by iv2resemblesGod** [axcsz/Collect#1]
小红书去广告模块在小红书8.14.1版本中使用有Map Local信息流把下方评论误杀的情况，不知您使用时有没有
我这里发现是这条引起的
^https:\/\/edith\.xiaohongshu\.com\/api\/sns\/v[23]\/note\/(feed|redtube|videofeed)\? data="https://github.com/Keywos/rule/raw/main/mocks/reject-dict.json"

**Comment by axcsz** [comment]
> 小红书去广告模块在小红书8.14.1版本中使用有Map Local信息流把下方评论误杀的情况，不知您使用时有没有 我这里发现是这条引起的 ^https://edith.xiaohongshu.com/api/sns/v[23]/note/(feed|redtube|videofeed)? data="https://github.com/Keywos/rule/raw/main/mocks/reject-dict.json"

修改了，你试试看
